### ISSUE TITLE
Auth это полный Ауф

### ISSUE THREAD

**Issue by AndrewGronin** [MindboxDevSchool/TryScrumTeam#20]
Как вы могли заметить, авторизация не удобна, жрет много кода,трудно читаема.
Думаю надо сделать отдельный класс(статик наверное),который по authData и имеющимся параметрам проверит законность изменений,а то вытягивать через eventID event, через него трэк, и только потом смотреть на creatorId это уже перебор,
пока ладно, но в следующем спринте надо будет так сделать

**Comment by moskovets** [comment]
авторизация не предполагает проверки событий и треков. она только подтверждает, что userId соответствует токену. Но соглашусь, что она пока криво реализована.

Совсем другой вопрос в том, что нужно проверять, что человек действительно является создателем события и имеет право его удалять/редактировать - это уже логика событий. Для упрощения можно, например дублировать поле создателя в событие. В будущем у нас появится логика управления правами (платная/бесплатная версия). И тогда можно будет и над этой проблемой подумать.
